### ISSUE TITLE
Videos don't play!

### ISSUE THREAD

**Issue by magnuslsjoberg** [magnuslsjoberg/The-Filipino-Channel.bundle#1]
Login sequence is more or less correct but parameters and/or cookies need to be added when retrieving the media information.  May not be too much work left but unfortunately I don't have the time right now....

If anyone wants to take a shot, please feel free to do so!

**Comment by ptfir** [comment]
TFC kodi addon is now fixed. just want to update you guys. anybody who can try to fix the plex plugin? thank you po. 👌

**Comment by Sapphica** [comment]
Still not working for me :(

**Comment by nleoncio** [comment]
@magnuslsjoberg since the kodi plugin is now working, is there any chance this can be revisited and potentially get it back? I prefer the Plex plugin for TFC.

**Comment by magnuslsjoberg** [comment]
@niegel:

It may be... Unfortunately I am abroad until February and will not be able to try anything until I’m back...

**Comment by magnuslsjoberg** [comment]
Finally I have managed to login and can play the streams!  Unfortunately it is only working on Safari web browser, Plex Media Player and Chrome starts to transcode but I will look into that once I tidied up the login code. Please note that there is a lot of logging going on in this version. Please don't post logs since you may leak user information!!!

**Comment by nleoncio** [comment]
Glad to see you back in action on this. Looking forward to go back to
plex/tfc . Welcome back Magnuslsjoberg!

Niegel

**Comment by magnuslsjoberg** [comment]
Thank you!  We were away for 2.5 months (in the Philippines) so I had to pause everything.

It has been a real struggle to get the login to work and to get all cookies correct but that part is working now so I just need to clean up the code and sort out the logging.

It may be that I can remove a lot of the calls now that I have it working.

Unfortunately the happiness is only partial since I get transcoding on Plex Media Player. The only player that seems to work is Safari.

**Comment by magnuslsjoberg** [comment]
Working on Safari web player and iOS (old player, not mpv).   May work on AppleTV!
Does NOT work on Plex Media Player (macos,RPi)

**Comment by magnuslsjoberg** [comment]
2.0.0 released!   Now working on Safari and Chrome (macos), PMP (macos,RPi) and iOS.
NOTE! Due to the tedious login procedure it sometimes takes a very long time for a stream to start!

Once I tested a bit more, I will remove some logging and also try to optimize the code.
