### ISSUE TITLE
Problem playing video

### ISSUE THREAD

**Issue by nleoncio** [magnuslsjoberg/The-Filipino-Channel.bundle#12]
I noticed tfc.tv site went down last night and today i'm not able to play any video. I can get to the episode list but I've been getting error on playing video and is suggesting to restart plex server and on my plex viewer. I did that but it did not help. Anybody else getting this issue?

**Comment by Drucio** [comment]
yeah confirmed just tried it now. its broken again =\

**Comment by magnuslsjoberg** [comment]
TFC has changed their login and media handling.

Version 1.0.9 just released should fix all issues!

**Comment by nleoncio** [comment]
What does that mean for our beloved plugin?

**Comment by magnuslsjoberg** [comment]
@nleoncio:

That it now should work as usual again      = ]

**Comment by nleoncio** [comment]
Awesome!!!

**Comment by magnuslsjoberg** [comment]
Fixed in v1.0.9

**Comment by magnuslsjoberg** [comment]
I guess I was too excited too early...

I get transcoding on my RPi which I didn’t get before. macos and iPhone work though.

**Comment by Drucio** [comment]
Hey 6/30/2018 at 7PM i think its broken again anyone else with issues???

**Comment by nleoncio** [comment]
Its working on my android. Wont be able to check on a desktop til later

**Comment by Drucio** [comment]
False arm... I guess it just stopped working for a bit...

**Comment by magnuslsjoberg** [comment]
Just released v1.0.10 with a minor fix for a TFC change.

**Comment by nleoncio** [comment]
I don't see a new release in Github. Is the fix somewhere else?

**Comment by Drucio** [comment]
I don't see the update either

**Comment by magnuslsjoberg** [comment]
Sorry guys! I forgot to push the commit to GitHub.....

Thanks for reporting.

**Comment by nleoncio** [comment]
Working now. Thanks a bunch.

**Comment by magnuslsjoberg** [comment]
Btw, my transcoding problem with RPi was a bug in PMP 2.10 backing to 2.9 nightly build solved the issue
