### ISSUE TITLE
No content found

### ISSUE THREAD

**Issue by jteagueuk** [magnuslsjoberg/The-Filipino-Channel.bundle#3]
Hi,

Everything was working since I installed but today im getting no content found error browsing any of the shows.  Live TV seems to still be working.  I can watch ANC live ok just all the shows are missing episodes.

**Comment by magnuslsjoberg** [comment]
Same here!  Ay grabeh! I will try to look into it during the weekend. TFC must have updated their website again...

**Comment by Drucio** [comment]
Same... =\

**Comment by magnuslsjoberg** [comment]
Just tested a few shows on their website and it works perfectly well.

Time for some reverse engineering again =]

**Comment by magnuslsjoberg** [comment]
It seems like you have to login even to browse the website...
I have added the login (another ugly hack) and it seems to work.
Please test and report back!

**Comment by Drucio** [comment]
Works cool thanks!

**Comment by jteagueuk** [comment]
Just tried it and its working for me.  Thank you very much for the quick fix.

**Comment by magnuslsjoberg** [comment]
Re-opened since I get "too many logins" (as I was afraid of...) A bit silly but may need to logout after every time a video is played.

**Comment by magnuslsjoberg** [comment]
Fixed...
