### ISSUE TITLE
English Subtitle Support?

### ISSUE THREAD

**Issue by hypersnail** [magnuslsjoberg/The-Filipino-Channel.bundle#6]
First, thank you for your support and development of this channel! 

It may have been the film I was watching, but I couldn't find a way to enable English captions. If captions/subtitles is not currently supported, I'd like to submit it as a feature request. I have never submitted a feature request, so apologies in advanced if this is an improper way of doing so.

**Comment by magnuslsjoberg** [comment]
@hypersnail:
Sorry for the late reply!  There is no way to add subtitles to the streamed content from TFC.
There are however some subtitled shows under "Shows - Subtitled Shows"

**Comment by magnuslsjoberg** [comment]
Not possible.
